# Generated by Django 5.2.4 on 2025-08-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categroy',
            new_name='Category',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='shop_catego_name_289c7e_idx',
            old_name='shop_categr_name_de9f9e_idx',
        ),
    ]
